export const GET_BLOG_LIST = "GET_BLOG_LIST";
export const GET_SPOTTED_BLOG = "GET_SPOTTED_BLOG";
export const GET_BLOG_DETAIL_BYID = "GET_BLOG_DETAIL_BYID";
export const ADD_BLOG = "ADD_BLOG";
export const EDIT_BLOG_BY_ID = "EDIT_BLOG_BY_ID";
export const UPDATE_TO_BE_EDITED_VALUE_FROM_SESSION_STORAGE =
  "UPDATE_TO_BE_EDITED_VALUE_FROM_SESSION_STORAGE";
