export const GET_INVENTORY_LIST = "GET_INVENTORY_LIST";
export const GET_BATCH_LIST = "GET_BATCH_LIST";
export const DELETE_BATCH = "DELETE_BATCH";
export const GET_INVENTORY_WAREHOUSES_LIST = "GET_INVENTORY_WAREHOUSES_LIST";
export const GET_BATCH_DETAIL = "GET_BATCH_DETAIL";
