export const styles = {
  headerTextContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  headerText: {
    fontSize: "0.9rem",
    color: "#5B5B5B",
    fontWeight: 600,
    lineHeight: "1.2rem",
  },
  subHeaderText: {
    fontSize: "0.8rem",
    color: "#898B87",
    fontWeight: 500,
    lineHeight: "1.2rem",
  },
  uploadText: {
    fontSize: "0.8rem",
    color: "black",
    fontWeight: 400,
    lineHeight: "1.2rem",
  },
  uploadImgContainer: (productImg, defaultImg) => ({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "#F0F5EC",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    borderRadius: "10px",
    border: productImg ? `0` : defaultImg ? `0` : "1px dashed #6D9E3F",
    cursor: "pointer",
    position: "relative",
  }),
  uploadImg: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "0.5rem",
    width: "10rem",
    height: "6rem",
    cursor: "pointer",
  },
  uploadedImg: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "10rem",
    height: "6rem",
    borderRadius: "10px",
    // cursor: "none",
  },
  uploadParentContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    // gap: "2rem",
    flexWrap: "wrap",
    marginTop: "1rem",
  },
  primaryImgContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "0.5rem",
    margin: "0.5rem 0 1rem 0",
  },
  primaryImgText: {
    fontSize: "0.8rem",
    // color: "#898B87",
    fontWeight: 500,
    lineHeight: "1.2rem",
  },
  deleteIconContainer: {
    position: "absolute",
    top: 0,
    right: 0,
    // padding: "0.5rem",
    zIndex: 99,
  },
  deleteIcon: {
    // width: "1.5rem",
    borderRadius: "0 5px 0 0",
    cursor: "pointer",
  },
};
