export const GET_FINANCE_REQUEST_DETAIL = "GET_FINANCE_REQUEST_DETAIL";
export const GET_ACTIVE_REQUESTS_LIST = "GET_ACTIVE_REQUESTS_LIST";
export const GET_CLOSED_REQUESTS_LIST = "GET_CLOSED_REQUESTS_LIST";
export const GET_ASSOCIATION_SALE_LIST = "GET_ASSOCIATION_SALE_LIST";
export const GET_FARMER_INFO_LIST = "GET_FARMER_INFO_LIST";
export const GET_FARMER_INFO_DETAIL = "GET_FARMER_INFO_DETAIL";
export const GET_ASSOCIATION_HARVEST_LIST = "GET_ASSOCIATION_HARVEST_LIST";
