export const GET_INPUT_ACTIVE_ADS_LIST = "GET_INPUT_ACTIVE_ADS_LIST";
export const GET_INPUT_ORDER_LIST = "GET_INPUT_ORDER_LIST";
export const GET_ORDER_DETAIL_BY_ID = "GET_ORDER_DETAIL_BY_ID";
export const GET_INPUT_ACTIVE_AD_DETAIL_BY_ID =
  "GET_INPUT_ACTIVE_AD_DETAIL_BY_ID";
export const GET_INPUT_DETAILS = "GET_INPUT_DETAILS";
export const LOADING_INPUT = "LOADING_INPUT";
export const LOADING_INPUT_LANDING_PAGE = "LOADING_INPUT_LANDING_PAGE";
