export const ADD_LAND = "ADD_LAND";
export const UPDATE_LAND = "UPDATE_LAND";
export const ADD_FARMER_PERSONAL_DETAIL_ACTION =
  "ADD_FARMER_PERSONAL_DETAIL_ACTION";
export const RESET_ADD_FARMER_PERSONAL_DETAILS =
  "RESET_ADD_FARMER_PERSONAL_DETAILS";
export const UPDATE_ADD_FARMER_PERSONAL_DETAILS =
  "UPDATE_ADD_FARMER_PERSONAL_DETAILS";
export const SELECTED_REFEREES_DATA = "SELECTED_REFEREES_DATA";
export const COMPLETE_REFEREE_OTP_DETAILS = "COMPLETE_REFEREE_OTP_DETAILS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_FARMER_LIST = "GET_FARMER_LIST";
export const FARMER_OTP_DATA = "FARMER_OTP_DATA";
export const FARMER_OTP_ID = "FARMER_OTP_ID";
export const ADD_FARMER = "ADD_FARMER";
export const SET_LAND_DATA_BY_ID = "SET_LAND_DATA_BY_ID";
export const SET_PRODUCT_DATA_BY_FARMER_ID = "SET_PRODUCT_DATA_BY_FARMER_ID";
