export const GET_FARMING_ASSOCIATION = "GET_FARMING_ASSOCIATION";
export const GET_FARMER_REFEREE_LIST = "GET_FARMER_REFEREE_LIST";
export const GET_REFEREE_FARMER_DETAILS = "GET_REFEREE_FARMER_DETAILS";
export const GET_FARMER_DETAILS = "GET_FARMER_DETAILS";
