export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_LENGTH = "PRODUCTS_LENGTH";

export const GET_PRODUCT_ORDERS_QA_ADMIN = "GET_PRODUCT_ORDERS_QA_ADMIN";
export const GET_PRODUCT_ORDERS_QA_ADMIN_LENGTH = "GET_PRODUCT_ORDERS_QA_ADMIN_LENGTH";
export const GET_PRODUCT_ORDERS_QA_ADMIN_DETAILS =
  "GET_PRODUCT_ORDERS_QA_ADMIN_DETAILS";
export const GET_PRODUCT_ORDER_QA = "GET_PRODUCT_ORDER_QA";