export const CREATE_MARKETPLACE_AD = "CREATE_MARKETPLACE_AD";
export const GET_ACTIVE_ADS_LIST = "GET_ACTIVE_ADS_LIST";
export const GET_ACTIVE_ADS_DETAIL = "GET_ACTIVE_ADS_DETAIL";
export const GET_RECIEVED_ORDERS_LIST = "GET_RECIEVED_ORDERS_LIST";
export const GET_RECIEVED_ORDER_DETAIL = "GET_RECIEVED_ORDER_DETAIL";
