export const GET_FINANCE_REQUEST_DETAIL_BY_ID =
  "GET_FINANCE_REQUEST_DETAIL_BY_ID";
export const GET_FIN_REQ_FOR_PRODUCT_LIST = "GET_FIN_REQ_FOR_PRODUCT_LIST";
export const GET_FIN_REQ_FOR_INPUT_LIST = "GET_FIN_REQ_FOR_INPUT_LIST";
