export const GET_FAQ_LIST = "GET_FAQ_LIST";
export const ADD_FAQ = "ADD_FAQ";
export const EDIT_FAQ_BY_ID = "EDIT_FAQ_BY_ID";
export const UPDATE_TO_BE_EDITED_VALUE_FROM_SESSION_STORAGE =
  "UPDATE_TO_BE_EDITED_VALUE_FROM_SESSION_STORAGE";
