export const GET_ADMIN_REPORTS_LIST = "GET_ADMIN_REPORTS_LIST";
export const GET_ADMIN_REPORTS_INPUT_LIST = "GET_ADMIN_REPORTS_INPUT_LIST";
export const GET_ADMIN_REPORTS_USERS_LIST = "GET_ADMIN_REPORTS_USERS_LIST";
