export const GET_COUNTRIES = " GET_COUNTRIES";
export const IS_LOADING_COUNTRY_DATA = "IS_LOADING_COUNTRIES";
export const IS_ERROR_GETTING_COUNTRY_DATA = "IS_ERROR_GETTING_COUNTRY_DATA";
export const SET_COUNTRY_ID = "SET_COUNTRY_ID";
export const SET_COUNTRY_CODE = "SET_COUNTRY_CODE";
export const SET_CODE_OF_COUNTRY = "SET_CODE_OF_COUNTRY";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
