export const GET_ALL_SUBSCRIPTIONS = "GET_ALL_SUBSCRIPTIONS";
export const ALL_SUBSCRIPTIONS_LENGTH = "ALL_SUBSCRIPTIONS_LENGTH";
export const ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION";
export const SUBSCRIPTION_CURRENCY = 'SUBSCRIPTION_CURRENCY';
export const FARMERS_SUBSCRIPTION = "FARMERS_SUBSCRIPTION";
export const FARMERS_SUBSCRIPTION_INFO = "FARMERS_SUBSCRIPTION_INFO";
export const FARMERS_SUBSCRIPTION_DETAIL = "FARMERS_SUBSCRIPTION_DETAIL";
export const FARMERS_SUBSCRIPTION_INDEX = "FARMERS_SUBSCRIPTION_INDEX";