export const GET_TRUCK_LIST = "GET_TRUCK_LIST";
export const GET_TRUCK_DETAILS = "GET_TRUCK_DETAILS";
export const ADD_TRUCK = "ADD_TRUCK";
export const GET_REQUEST_ACCESS_DATA = "GET_REQUEST_ACCESS_DATA";
export const GET_INPUT_LIST_LENGTH = "GET_INPUT_LIST_LENGTH";
export const GET_PRODUCT_LIST_LENGTH = "GET_PRODUCT_LIST_LENGTH";
export const GET_TRANSIT_INPUT_LIST = "GET_TRANSIT_INPUT_LIST";
export const GET_TRANSIT_PRODUCT_LIST = "GET_TRANSIT_PRODUCT_LIST";
export const GET_TRANSIT_ORDERS_DETAIL_BY_ID =
  "GET_TRANSIT_ORDERS_DETAIL_BY_ID";
export const GET_TRANSIT_ORDERS_DETAIL_INPUT_BY_ID =
  "GET_TRANSIT_ORDERS_DETAIL_INPUT_BY_ID";
export const GET_ADS_INPUT_LIST = "GET_ADS_INPUT_LIST";
export const GET_ADS_PRODUCT_LIST = "GET_ADS_PRODUCT_LIST";
