export const GET_TRADING_ACTIVE_ADS = "GET_TRADING_ACTIVE_ADS";
export const GET_TRADING_ACTIVE_AD_DETAIL_BY_ID =
  "GET_TRADING_ACTIVE_AD_DETAIL_BY_ID";
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const GET_ORDER_DETAIL_BY_ID = "GET_ORDER_DETAIL_BY_ID";

export const GET_TRADING_ORDER_LIST = "GET_TRADING_ORDER_LIST";
export const GET_TRADING_INPUT_ORDER_LIST = "GET_TRADING_INPUT_ORDER_LIST";
export const GET_TRADING_ACTIVE_AD_LANDING_PAGE = "GET_TRADING_ACTIVE_AD_LANDING_PAGE";
export const GET_PRODUCT_LIST_LANDING_PAGE = "GET_PRODUCT_LIST_LANDING_PAGE";
export const GET_INPUT_LIST_LANDING_PAGE = "GET_INPUT_LIST_LANDING_PAGE";
export const GET_ALL_PRODUCT_OPENMARKETPLACE = "GET_ALL_PRODUCT_OPENMARKETPLACE";
export const GET_ALL_PRODUCT_OPENMARKETPLACE_DETAILS_BY_ID =
  "GET_ALL_PRODUCT_OPENMARKETPLACE_DETAILS_BY_ID";
export const LOADING = 'LOADING';
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const LOADING_PRODUCT_LANDING_PAGE = "LOADING_PRODUCT_LANDING_PAGE";
